export { default as Bio } from './Bio'
export { default as Footer } from './Footer'
export { default as Layout } from './Layout'
export { default as Image } from './Image'
export { default as SEO } from './seo'
export { default as Code } from './code'
